# 2018년 3월 28일 점프투파이썬 2장
## 테스트
- 숫자형
    1. 기능1
    2. 기능2
- 문자형
- 리스트

1. 숫자형
2. 문자형

In [4]:
print("3번째 수업")

3번째 수업


In [2]:
123

123

## 1절 숫자형

In [6]:
123

123

In [7]:
456

456

In [8]:
1+2

3

In [9]:
123124*2342

288356408

In [10]:
7/4

1.75

In [13]:
-7/4

-1.75

In [12]:
7//4

1

In [1]:
-7//4

-2

In [14]:
7%4

3

In [19]:
A=80 
B=75
C=55
(A+B+C)/3

70.0

In [21]:
17//3

5

In [22]:
17%3

2

In [15]:
1-0.9

0.09999999999999998

### Lab1 1
#### 수익 계산
    - 변수 revenue를 생성 후 98456 할당
    - 변수 cost를 생성 후 45000 할당
    - 변수 profit을 생성 후, revenue와 cost 차이 값으로 설정
    - profit 출력

In [30]:
revenue=98456
cost=45000
profit=revenue-cost
print(profit)

53456


## 2절 문자열

In [17]:
boy="I am a boy"
boy

'I am a boy'

In [18]:
girl='I am a girl'
girl

'I am a girl'

In [19]:
"I'm a boy"

"I'm a boy"

In [20]:
friend="""
I am a boy
I am a girl
"""
friend

'\nI am a boy\nI am a girl\n'

In [27]:
boy+girl

'I am a boyI am a girl'

In [23]:
boy+' '+girl

'I am a boy I am a girl'

In [24]:
boy*3

'I am a boyI am a boyI am a boy'

In [23]:
a = "Life is short, you need Python"
a[0]

'L'

In [24]:
a[11]

'r'

In [25]:
a[0]+a[11]

'Lr'

In [26]:
a[0:4]+a[19:23]

'Lifeneed'

In [27]:
a[:5]

'Life '

In [28]:
a[19:]

'need Python'

### lab2
#### 문자열 다루기
- 변수 a를 생성해서, 문자열 "I love Python!"
- 변수 b를 생성해서, 문자열 "You hate Python!"

In [32]:
a="I love Python"
a

'I love Python'

In [34]:
b="You hate Python"
b

'You hate Python'

#### 인덱싱

In [66]:
# 문자열 인덱싱
a= "Life is short. You need Python"
a[0] + a[10] + a[20]

'Loe'

In [67]:
# 문자열 슬라이싱
a[:18]

'Life is short. You'

In [49]:
a[:]

'Life is short. You need Python'

In [48]:
a[1:]

'ife is short. You need Python'

In [62]:
a="20180328Sunny"
year = a[:4]
month = a[4:6]
day = a[6:8]
weather = a[8:]
year
month
day
weather

'Sunny'

In [63]:
year

'2018'

In [57]:
month

'03'

In [59]:
day

'28'

In [60]:
weather

'Sunny'

In [61]:
print(year, month, day, weather)

2018 03 28 Sunny


In [69]:
print(year, "년", month, "월", day, "일", weather, "입니다")

2018 년 03 월 28 일 Sunny 입니다


In [72]:
"year년 month월 day일 weather입니다"

'year년 month월 day일 weather입니다'

In [75]:
"{year}년 {month}월 {day}일 {weather}입니다".format(month=month, day=day, weather=weather, year=year)

'2018년 03월 28일 Sunny입니다'

### 문자열 내장함수

In [87]:
#
a="Hobby"
a.count("b")

2

In [90]:
a="나는 나다."
a.count("나")

2

In [103]:
#위치 알려주기
a="hobby"
a.find("b")

2

In [99]:
# 위치 알려주기2
a.index("b")

2

In [106]:
# 문자 삽입하기
a = ", "
a.join("금은동")

'금, 은, 동'

In [110]:
# 대문자로
a = "I love Python"
a.upper()

'I LOVE PYTHON'

In [111]:
# 소문자로
a = "I love Python"
a.lower()

'i love python'

In [129]:
# 왼쪽 공백 지우기
a = "    Hi~"
a.lstrip()

'Hi~'

In [115]:
#오른쪽 공백 지우기
a = "Hi~      "
a.rstrip()

'Hi~'

In [117]:
a = "    Hi~   "
a.strip()

'Hi~'

In [120]:
# 문자열 나누기
a = "Life is too short"
a.split()

['Life', 'is', 'too', 'short']

In [46]:
print(""""점프 투 파이썬"문제를 풀어보자""")

"점프 투 파이썬"문제를 풀어보자


In [47]:
print("""
Life is too short
You need Python
""")


Life is too short
You need Python



In [48]:
a = "a:b:c:d"
b = "#"
print(b.join(a.split(':')))

a#b#c#d


## Lab2 이어서
- 변수 a를 생성하여, 문자열 "I love Python"을 할당하시오
- 변수 b를 생성하여, 문자열 "I hate Python"을 할당하시오
a = "I love Python"
b = "I hate Python"

In [143]:
a = "I love Python"
b = "I hate Python"

- a에서 첫번째 o의 위치를 find()함수로 찾아보시오.
- b에서 첫번째 o의 위치를 index()함수로 찾아보시오.
- a의 'o' 문자 개수를 구하시오.

In [122]:
a.find("o")

3

In [132]:
b.index("o")

11

In [124]:
a.count("o")

2

- 변수 a를 모두 대문자로 바꿔보시오.
- 변수 b를 모두 소문자로 바꿔보시오.

In [126]:
a.upper()

'I LOVE PYTHON'

In [127]:
b.lower()

'i hate python'

- 변수 a.6에 a의 첫 7글자들로 이루어진 부분 문자열을 할당하시오.
- 변수 a의 문자열을 공백을 이용해서 나눠보시오.

In [150]:
a_6 = a[0:7]
a_6

'I love '

In [154]:
a_6.rstrip()

'I love'

In [155]:
a.split()

['I', 'love', 'Python']

### lab3
#### 문자열 포메팅
- 변수 pi을 생성하고 3.141592를 할당하시오.
- 변수 sq_root를 생성하고 1b.41429를 할당하시오.

In [125]:
pi=3.141592
sq_root=1.41429
print(pi, sq_root)

3.141592 1.41429


#### 다음의 출력을 포메팅을 사용하여 만드시오
- pi is 3.141592 and square root of 2 is 1.41429

In [84]:
"pi is {pi} and square root of 2 is {sq_root}".format(pi=pi, sq_root=sq_root)

'pi is 3.141592 and square root of 2 is 1.41429'

## 3절 리스트